---
- name: Install and configure UFW firewall
  hosts: wireguard_servers
  become: true

  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow SSH (port 22)
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Allow HTTP (port 80)
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allow HTTPS (port 443)
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Allow WireGuard (port 51820/udp)
      community.general.ufw:
        rule: allow
        port: 51820
        proto: udp

    - name: Enable UFW firewall
      community.general.ufw:
        state: enabled
